---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-demo
  labels:
    # Allow CSI driver to work in this namespace
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

# Made with Bob
