---
apiVersion: v1
kind: Service
metadata:
  name: vault-demo-app
  namespace: vault-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: vault-demo-app
spec:
  type: ClusterIP
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: vault-demo-app

# Made with Bob