---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets
  namespace: openshift-gitops
spec:
  project: default
  
  sources:
    - repoURL: https://github.com/breznada/vault-openshift-demo.git
      targetRevision: main
      path: k8s/vault-crds
  
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-demo
  
  ignoreDifferences:
    - group: secrets.hashicorp.com
      kind: VaultDynamicSecret
      name: vault-dynamic-secret
      namespace: vault-demo
      jqPathExpressions:
        - .spec.revocationAfter
        - .spec.renewalPercent

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

# Made with Bob
